version: '3'
services:
  wordpress:
    image: wordpress:5.9
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_pass

  mysql:
    image: mysql:8.0.42
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_pass
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_pass
    volumes:
      - wordpress_mysql:/var/lib/mysql

volumes:
  wordpress_data:
  wordpress_mysql:
